export const teamMembers = [
  {
    name: "Ganesh Asapu",
    title: "Founding Engineer",
    photo: "/people/ganesh.jpg",
    legend: "/people/ganesh-legend.jpg",
    photoBg: "#4338CA",
    legendBg: "#4338CA",
    linkedin: "#",
    bio: "Former ML engineer at Cohere, Voiceflow, and Wisedocs. Built SOTA LLMs, shipped AI agents into finance, healthcare, and insurance, and somehow still likes datasets.",
  },
  {
    name: "Grant Harvey",
    title: "Founding GTM",
    photo: "/team/grant-harvey.R62T2ZCI_1Pie6y.webp",
    legend: "/team/grant-harvey-greek.CQc_ymeZ_Z1GFnMN.webp",
    photoBg: "#4338CA",
    legendBg: "#E8E4DA",
    linkedin: "#",
    bio: "Grant enjoys long walks on the golf course when he is not helping folks crush their GEO goals. Some say he does everything possible to avoid the tech elite of San Francisco, so he lives in Palo Alto. He will always find a way to tell you he played D1 college sport and how much his back hurts. When people ask him where he went to college, he just shrugs his shoulders and says a small school in Boston.",
  },
  {
    name: "Merrick Liu",
    title: "Founding Engineer",
    photo: "/people/merrick.jpg",
    legend: "/people/merrick-legend.jpg",
    photoBg: "#4338CA",
    legendBg: "#4338CA",
    linkedin: "#",
    bio: "Former engineer at Mercury. Built AI tools and researched biologically plausible deep learning. Will graduate from the University of Toronto at some point.",
  },
  {
    name: "James Moreno",
    title: "Founding GTM",
    photo: "/people/james.jpg",
    legend: "/people/james-legend.jpg",
    photoBg: "#4338CA",
    legendBg: "#4338CA",
    linkedin: "#",
    bio: "Focused on driving growth and partnerships. Loves storytelling, coffee, and long hikes that somehow end in business pitches.",
  },
  {
    name: "Renan Serrano",
    title: "Founding Evangelist",
    photo: "/people/renan.jpg",
    legend: "/people/renan-legend.jpg",
    photoBg: "#4338CA",
    legendBg: "#4338CA",
    linkedin: "#",
    bio: "Winner of 12+ awards including Singularity University and SXSW. Helps brands scale responsibly while advocating sustainable innovation.",
  },
  {
    name: "Andrew Yan",
    title: "CEO",
    photo: "/people/andrew.jpg",
    legend: "/people/andrew-legend.jpg",
    photoBg: "#4338CA",
    legendBg: "#4338CA",
    linkedin: "#",
    bio: "Former Google Search product manager. Worked on the next generation of AI Search and DeepMind’s generative media team.",
  },
] as const;
