export const teamMembers = [
  {
    name: "Nikita Clark",
    title: "President/Founder",
    photo: "/team/nikita_main.webp",
    legend: "/team/nikita-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/nikitaclark315/",
    bio: "Founder and visionary leader driving the company's mission and strategic direction.",
  },
  {
    name: "Kabir Israni",
    title: "Advisor",
    photo: "/team/kabir_main.webp",
    legend: "/team/kabir-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/kabirisrani/",
    bio: "Strategic advisor helping shape business strategy and growth initiatives.",
  },
  {
    name: "Ayush Shenvi Pissurlenkar",
    title: "Technical Advisor",
    photo: "/team/ayush_main.webp",
    legend: "/team/ayush-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/ayush-shenvipissurlenkar/",
    bio: "Providing strategic technical guidance and expertise to drive technological advancement.",
  },
  {
    name: "Anton Vinogradov",
    title: "Head of Engineering",
    photo: "/team/anton_main.webp",
    legend: "/team/anton-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/vinogradovanton/",
    bio: "Leading engineering excellence and innovation. Passionate about building scalable solutions and mentoring teams.",
  },
  {
    name: "Muhammad Haris",
    title: "Head Of Design",
    photo: "/team/haris_main.webp",
    legend: "/team/haris-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "https://www.linkedin.com/in/muhammadharys/",
    bio: "Crafting exceptional user experiences and leading design innovation across all products.",
  },
] as const;
