export const teamMembers = [
  {
    name: "Nikita Clark",
    title: "President/Founder",
    photo: "/team/grant-harvey.R62T2ZCI_1Pie6y.webp",
    legend: "/team/nikita-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "#",
    bio: "Founder and visionary leader driving the company's mission and strategic direction.",
  },
  {
    name: "Kabir Israni",
    title: "Advisor",
    photo: "/team/image2.png",
    legend: "/team/kabir-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "#",
    bio: "Strategic advisor helping shape business strategy and growth initiatives.",
  },
  {
    name: "Ayush Shenvi Pissurlenkar",
    title: "Technical Advisor",
    photo: "/team/image1.png",
    legend: "/team/ayush-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "#",
    bio: "Providing strategic technical guidance and expertise to drive technological advancement.",
  },
  {
    name: "Anton Vinogradov",
    title: "Head of Engineering",
    photo: "/team/image.png",
    legend: "/team/anton-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "#",
    bio: "Leading engineering excellence and innovation. Passionate about building scalable solutions and mentoring teams.",
  },
  {
    name: "Muhammad Haris",
    title: "Head Of Design",
    photo: "/team/image3.png",
    legend: "/team/haris-legend.webp",
    photoBg: "#1E2F5E",
    legendBg: "#E8E4DA",
    linkedin: "#",
    bio: "Crafting exceptional user experiences and leading design innovation across all products.",
  },
] as const;
